export default {
  index: 'Overview',
  quickstart: 'Quick Start',
  authentication: 'Authentication',
  'get-api-key': 'Get API Key',
  'story-guide': 'Story Guide',
  'story-reference': 'Story Reference',
  'story-use-cases': 'Story Use Cases',
  'thesis-guide': 'Thesis Guide',
  'thesis-use-cases': 'Thesis Use Cases',
  concepts: 'Core Concepts',
  'api-reference': 'API Reference',
  sdk: 'SDKs',
  guides: 'Guides',
  changelog: 'Changelog',
};
